# Static Defaults
replicaCount: 1
image:
  repository: 'docker.io/hightec'
  name: smo-nts-ng-topology-server
  tag: 1.3.3
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 2Gi

service:
  type: NodePort
  ports:
    port: 830
    nodePort: 30832

# Names
vnf_name: topology-server

simulatedFaults:
  - name: O-RU-11221
    condition: "CPRI Port Down"
    severity: MAJOR
    object: "Slot-0-Port-A"
    specificProblem: "CPRI Port Down"
    faultSeverity: MAJOR
    cleared: false
    text: "CPRI Port Down"
  - name: O-RU-11221
    condition: "CPRI Port Down"
    severity: NORMAL
    object: "Slot-0-Port-A"
    specificProblem: "CPRI Port Down"
    faultSeverity: MAJOR
    cleared: true
    text: "CPRI Port Down"
  - name: O-RU-11221
    condition: "CPRI Port Down"
    severity: MAJOR
    object: "Slot-0-Port-C"
    specificProblem: "CPRI Port Down"
    faultSeverity: MAJOR
    cleared: false
    text: "CPRI Port Down"
  - name: O-RU-11221
    condition: "CPRI Port Down"
    severity: NORMAL
    object: "Slot-0-Port-C"
    specificProblem: "CPRI Port Down"
    faultSeverity: MAJOR
    cleared: true
    text: "CPRI Port Down"
  - name: O-RU-11221
    condition: "CPRI Port Down"
    severity: MAJOR
    object: "Slot-2-Port-B"
    specificProblem: "CPRI Port Down"
    faultSeverity: MAJOR
    cleared: false
    text: "CPRI Port Down"
  - name: O-RU-11221
    condition: "CPRI Port Down"
    severity: NORMAL
    object: "Slot-2-Port-B"
    specificProblem: "CPRI Port Down"
    faultSeverity: MAJOR
    cleared: false
    text: "CPRI Port Down"

nodes:
  - name: highstreet-O-DU-1122
    uuid: ac089635-7a85-4197-9310-9b14f476a4a9
    nodeEdgePointUuid: 539f24cb-a5e9-454f-b05d-6307be419afe
    interfaceName: "O-DU-interface-1"
    interfaceDescription: "Simulated interface for O-DU"
  - name: highstreet-O-RU-11221
    uuid: 6b0d3930-100b-466c-9f44-2748ffb6aaa1
    nodeEdgePointUuid: bb7e5882-6e3a-46a7-a95b-0bb7310ede22
    interfaceName: "09a95e08-5b53-4734-815f-a9c12300fc62"
    interfaceDescription: "Simulated interface for O-RU"
  - name: highstreet-O-RU-11222
    uuid: 69a8fdf0-2bdd-44a2-9bc4-8813640fa02c
    nodeEdgePointUuid: 124488fc-05d0-421b-8a16-4eaf86cbc89b
    interfaceName: "0d242150-33a6-4e7c-9988-ae3b01e8a7ea"
    interfaceDescription: "Simulated interface for O-RU"
  - name: highstreet-O-RU-11223
    uuid: c8499a83-211e-4cef-be30-a1cc2208bbb6
    nodeEdgePointUuid: 5f01a4c2-9067-4b05-a1a5-7d8998f4f11f
    interfaceName: "d3ea2f17-a841-4e71-9ef9-9549159aabe7"
    interfaceDescription: "Simulated interface for O-RU"

topologyUuid: 7adfee73-44be-4813-a0dc-89f657f0a436
links:
  - duNode: highstreet-O-DU-1122
    ruNode: highstreet-O-RU-11221
    uuid: ac78b69f-22df-46fd-ae76-cc989bc30abc
  - duNode: highstreet-O-DU-1122
    ruNode: highstreet-O-RU-11222
    uuid: ac78b69f-22df-46fd-ae76-cc989bc30ae9
  - duNode: highstreet-O-DU-1122
    ruNode: highstreet-O-RU-11223
    uuid: bc98b69f-22df-46fd-ae76-cc989bc30ae9

# NTS NG settings
ntsimNg:
  ipV6Enabled: true
  sshConnections: 1
  tlsConnections: 0
  ntsHostIp: 2a00:7b80:454:2000::2
  ntsHostBasePort: 50000
  ntsHostNetconfSshBasePort: 0
  ntsHostNetconfTlsBasePort: 1000
  ntsHostTransferFtpBasePort: 2000
  ntsHostTransferSftpBasePort: 2000
  ntsNfMountPointAddressingMethod: docker-mapping

  sdnControllerProtocol: http
  sdnControllerCallHomePort: 6666
  sdnControllerUsername: admin
  sdnControllerPassword: Kp8bJ4SXszM0WXlhak3eHlcse2gAw84vaoGGmJvUy2U
  sdnControllerPort: 8181
  sdnControllerIp: 2001:db8:1:50::27

  vesCommonHeaderVersion: 7.2.1
  vesEndpointProtocol: https
  vesEndpointIp: 2001:db8:1:50::27
  vesEndpointPort: 8443
  vesEndpointAuthMethod: basic-auth
  vesEndpointUsername: sample1
  vesEndpointPassword: sample1

  ntsNfStandaloneStartFeatures: datastore-populate netconf-call-home web-cut-through
