# Static Defaults
replicaCount: 1
image:
  repository: 'docker.io/hightec'
  name: smo-nts-ng-topology-server
  tag: 1.3.3
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 2Gi

service:
  type: NodePort
  ports:
    port: 830
    nodePort: 30832

# Names
vnf_name: topology-server

# NTS NG settings
ntsimNg:
  ipV6Enabled: true
  sshConnections: 1
  tlsConnections: 0
  ntsHostIp: 2a00:7b80:454:2000::2
  ntsHostBasePort: 50000
  ntsHostNetconfSshBasePort: 0
  ntsHostNetconfTlsBasePort: 1000
  ntsHostTransferFtpBasePort: 2000
  ntsHostTransferSftpBasePort: 2000
  ntsNfMountPointAddressingMethod: docker-mapping

  sdnControllerProtocol: http
  sdnControllerCallHomePort: 6666
  sdnControllerUsername: admin
  sdnControllerPassword: Kp8bJ4SXszM0WXlhak3eHlcse2gAw84vaoGGmJvUy2U
  sdnControllerPort: 8181
  sdnControllerIp: 2001:db8:1:50::27

  vesCommonHeaderVersion: 7.2.1
  vesEndpointProtocol: https
  vesEndpointIp: 2001:db8:1:50::27
  vesEndpointPort: 8443
  vesEndpointAuthMethod: basic-auth
  vesEndpointUsername: sample1
  vesEndpointPassword: sample1

  ntsNfStandaloneStartFeatures: datastore-populate netconf-call-home web-cut-through
