# Static Defaults
replicaCount: 1
image:
  repository: 'nexus3.o-ran-sc.org:10002/o-ran-sc'
  name: nts-ng-o-ran-ru-fh 
  tag: 1.3.3
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 2Gi

service:
  type: NodePort
  ports:
    port: 667
    nodePort: 30667

# Names
vnf_name: ru-simulator
