# Copyright © 2022 AT&T Intellectual Property
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

testsSuite:
  jenkins: true
  tests: false

oranTests:
  name: orantests1
  flag: true
  commitId: 7b4b4007db003d28ee347e3d373e8ac605581cb5

github:
  username: testuser
  password: api-token

jenkins:
  controller:
    imagePullPolicy: "IfNotPresent"
    nodePort: 32080
    serviceType: NodePort
    additionalExistingSecrets:
      - name: github-secret-credentials
        keyName: username
      - name: github-secret-credentials
        keyName: password

    additionalPlugins: 
      - job-dsl:1.77
      - pipeline-githubnotify-step:1.0.5
      - ghprb:1.42.2
    JCasC:
      securityRealm: |-
        local:
          allowsSignup: false
          enableCaptcha: false
          users:
          - id: "test"
            name: "Jenkins Admin"
            password: "test"
      authorizationStrategy: |-
        loggedInUsersCanDoAnything:
          allowAnonymousRead: true
      defaultConfig: true
      configScripts:
        welcome-message: |
          jenkins:
            systemMessage: Welcome to the ORAN SMO Package embedded CI\CD server.  This Jenkins is configured and managed 'as code'.
        credentials: |
          credentials:
            system:
              domainCredentials:
              - credentials:
                - usernamePassword:
                    description: "github access username password"
                    id: "github_username_pass"
                    password: ${github-secret-credentials-password}
                    scope: GLOBAL
                    username: ${github-secret-credentials-username}
        views: |
          jenkins:
            views:
            - all:
                name: "all"
            - list:
                columns:
                - "status"
                - "weather"
                - "jobName"
                - "lastSuccess"
                - "lastFailure"
                - "lastDuration"
                - "buildButton"
                includeRegex: "github-manual.*"
                name: "github-manual"
            - list:
                columns:
                - "status"
                - "weather"
                - "jobName"
                - "lastSuccess"
                - "lastFailure"
                - "lastDuration"
                - "buildButton"
                includeRegex: "github-automatic.*"
                name: "github-automatic"

        pipeline-job: | 
          jobs:
            - script: >
                pipelineJob('github-manual-start-test') {
                  parameters {
                    stringParam('BRANCH',"*/main","Branch or Commit ID")
                  }
                  concurrentBuild(false)
                  description('This job is triggered manually to execute the SMO tests on the RUNNING SMO in the K8S cluster')
                  definition {
                    cpsScm {
                      scm {
                        git {
                          remote {
                            github('sebdet/oran-deployment')
                          }
                          branch('$BRANCH')
                          extensions { 
                            cleanBeforeCheckout()
                          }

                        }
                      }
                      scriptPath("jenkins/github/manual-tests-pipeline")
                    }
                  }
                } 
            - script: >
                pipelineJob('github-manual-start-smo') {
                  parameters {
                    stringParam('BRANCH',"*/main","Branch or Commit ID")
                  }
                  description('This job is triggered manually to start SMO in the K8S cluster')
                  concurrentBuild(false)
                  definition {
                    cpsScm {
                      scm {
                        git {
                          remote {
                            url('https://github.com/sebdet/oran-deployment.git')
                          }
                          branch('$BRANCH')
                          extensions {
                            cleanBeforeCheckout()
                          }
                        }
                      }
                      scriptPath("jenkins/github/manual-start-pipeline")
                    }
                  }
                }
            - script: >
                pipelineJob('github-manual-stop-smo') {
                  concurrentBuild(false)
                  description('This job is triggered manually to stop the running SMO in the K8S cluster')
                  definition {
                    cpsScm {
                      scm {
                        git {
                          remote {
                            url('https://github.com/sebdet/oran-deployment.git')
                          }
                          branch('*/main')
                        }
                      }
                      scriptPath("jenkins/github/manual-stop-pipeline")
                    }
                  }
                }
            - script: >
                pipelineJob('github-automatic-trigger-verify') {
                  concurrentBuild(false)
                  description('This job is triggered automatically when pull requests are opened on GITHUB.')
                  triggers {
                    githubPullRequest {
                      admin('test')
                      cron('* * * * *')
                      triggerPhrase('jenkinstest')
                      onlyTriggerPhrase()
                      userWhitelist(['sebdet'])
                      whiteListTargetBranches(['main'])
                    }
                  }
                  definition {
                    cpsScm {
                      scm {
                        git {
                          remote {
                            name('origin')
                            github('sebdet/oran-deployment')
                            refspec('+refs/pull/*:refs/remotes/origin/pr/*')
                          }
                          branch('${ghprbActualCommit}')
                        }
                      }
                      scriptPath("jenkins/github/automatic-verify-pipeline")
                    }
                  }
                }
            - script: >
                multibranchPipelineJob('github-automatic-trigger-verify2') {
                  description('This job is triggered automatically when pull requests are opened on GITHUB.')
                  triggers {
                    periodic(3)
                  }
                  branchSources {
                    github {
                      id('1') // IMPORTANT: use a constant and unique identifier
                      repoOwner('sebdet')
                      repository('oran-deployment')
                      scanCredentialsId('github_username_pass')
                      buildForkPRHead(false)
                      buildForkPRMerge(false)
                      buildOriginBranch(true)
                      buildOriginBranchWithPR(true)
                      buildOriginPRHead(true)
                      buildOriginPRMerge(false)
                    }
                  }
                  factory {

                    workflowBranchProjectFactory {
                      // Relative location within the checkout of your Pipeline script.
                      scriptPath("jenkins/github/automatic-verify-pipeline")
                    }
                  } 
                }

