# Copyright © 2022 AT&T Intellectual Property
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

testsSuite:
  jenkins: true
  tests: false
  chartmuseum: false

oran-tests:
  name: orantests1
  flag: true
  commitId: 7b4b4007db003d28ee347e3d373e8ac605581cb5

jenkins:
  controller:
    nodePort: 32080
    serviceType: NodePort
    additionalPlugins: 
      - job-dsl:1.77
    JCasC:
      securityRealm: |-
        local:
          allowsSignup: false
          enableCaptcha: false
          users:
          - id: "test"
            name: "Jenkins Admin"
            password: "test"
      authorizationStrategy: |-
        loggedInUsersCanDoAnything:
          allowAnonymousRead: true
      defaultConfig: true
      configScripts:
        welcome-message: |
          jenkins:
            systemMessage: Welcome to the ORAN SMO Package CI\CD server.  This Jenkins is configured and managed 'as code'.
        pipeline-job: | 
          jobs:
            - script: >
                pipelineJob('job-dsl-plugin') {
                  definition {
                    cpsScm {
                      scm {
                        git {
                          remote {
                            url('https://github.com/sebdet/oran-deployment.git')
                          }
                          branch('*/main')
                        }
                      }
                      scriptPath("jenkins/automated-tests-pipeline")
                    }
                  }
                } 
